### ISSUE TITLE
Program: Have experiment randomly generate balloons

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/CompetitiveBart#1]
We start by generating 100 random balloon popping time sheets (e.g.; trialtypes1.txt, trialtypes2.txt). We do this in R before running any studies. Each sheet has a vector of N popping times (where N is the number of balloons in the game)

Now, at the beginning of each game. Call one computer the master and one the slave. The Master starts by randomly selecting ONE of the popping time sheets. For example, it might select trialtypes8.txt. This sheet is then used for both computers as the popping trial for each balloon.

**Comment by ktrutmann** [comment]
Could we just input the sheet to be used at the start of the experiment. This would require less hacky comunications between the compuerts. So at the beginning the investigator would input the Participant Number and the Sheet to be used. As the sheets are already random, using them sequentialy shouldn't be a problem... right?

**Comment by ndphillips** [comment]
Sure! Sounds fine to me!

**Comment by ktrutmann** [comment]
Then this also done. I've also written a little R script to generate the .csv files with the popping times.
I don't think I can close down these issues, so you'll have to do that.

**Comment by ndphillips** [comment]
Great!
