### ISSUE TITLE
Program: Force players to wait for others to finish

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/CompetitiveBart#3]
We need to find a way such that when one player finishes, their computer checks to see if the other player is finished. If not, then the computer must wait.

For example, the computer will check every second to see if the other player's computer has written points for the current trial or not.

**Comment by ktrutmann** [comment]
Done, and works like a charm.

**Comment by ndphillips** [comment]
Fantastic! Looking forward to seeing it.
