### ISSUE TITLE
Programming: Don't use space bar to pump!

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/CompetitiveBart#4]
Space bar is too loud for pumping. Find the quietest key and use that!

**Comment by ktrutmann** [comment]
I've changed it to 'P' (for pump) for now. It's really easy to change.
Is that okay position wise?
And is it also quiet on those fancy apple keyboards?

**Comment by ndphillips** [comment]
We'll have to test it, but sounds good for now!
