### ISSUE TITLE
Add option to group balloons with `balloons.per.group`

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/CompetitiveBart#5]
I'd like to create versions of the game where players get feedback about their competitor's performance in 'blocks' of trials rather than every trial. Here's how I think this would work:

Create a new game parameter called `ballons.per.group`. The input to this is an integer from 1 to the total number of balloons in the game. This parameter dictates how many balloons players play until they receive feedback about how their competitor performed on the past `ballons.per.group` balloons.

In other words, `balloons.per.group` splits the total number of balloons into `balloon.total / balloons.per.group`groups of balloons. Players then play the same group of balloons at the same time, but not necessarily each balloon at the same time.

Because players should also receive feedback at the same time, players can never advance to the next group until both players have finished the past group and received feedback.

For example, if`balloons.per.group = 1`, then players receive competitive feedback about how they performed relative to their competitor after every balloon (e.g.; `In the past 1 balloon(s), you earned 10 points and your competitor earned 0 points`). This also means that players are always playing the same balloon at the same time

if `balloons.per.group= 10`, then players receive competitive feedback every 10 balloons about how they performed relative to their competitor. (e.g.; `In the last 10 balloons, you earned 30 points and your competitor earned 45 points`).

### Notes

- When `balloons.per.group` is greater than 1, players could be playing different balloons in the same group at different times. However, if one player finishes his group before his competitor, then he will have to wait for his competitor to finish that group before receiving feedback and moving on to the next group.

**Comment by ktrutmann** [comment]
Done
