### ISSUE TITLE
Add BART instructions

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/CompetitiveBart#9]
Please add a few introduction pages for the game with something along the following: (in german of course)

You might also consider contacting Oliver Shuermann (o.schuermann@unibas.ch) or Loreen (loreen.mamerow@unibas.ch) for existing German Bart instructions...

# Page 1

In this experiment, you will be competing against another participant in the Balloon Game. The player who earns the most points in the Balloon game will earn an extra bonus of 10CHF. The player who earns the least points will not earn an extra bonus.

Here's how the balloon game works. In the game, a balloon will appear on the screen and give you the chance to pump it by pressing the "p" key. Every time you pump a balloon, the balloon will fill up and you will earn an additional point. The more you pump a balloon, the larger it gets and the more points you will earn. However, there is a risk to pumping a balloon. If you pump a balloon too much, it will pop. If a balloon pops, you will lose all the points you earned for that balloon.

At any point, you can stop pumping a balloon by pressing enter. If you do this, then all of the points you earned for that balloon will be saved into your bank. Once points are in your bank, you can never lose them.

# Page 2

Each balloon is equally likely to pop from anywhere from 1 pump to 100 pumps. This means that if you try to pump it 100 times, it will definitely pop at some point. However, you will never know exactly when each balloon will pop.

You and your opponent will play the game in YY rounds. In each round, you will play ZZZ balloons. After each of you finish playing XX balloons in a round, you will learn how your opponent did in that round, and how you did.

Once all YY rounds are finished, the game will end. The player with the most points in the entire game will then earn an extra bonus of 10CHF. If both of you end with the same number of points, neither of you will earn the bonus.

# Page 3

If you have any questions about the game, please ask the experimenter now.

When you are ready, click continue to start a practice game. In this practice game, you will play 5 balloons against your opponent.

The points in the practice game don't matter, so feel free to play around to see how the game works.

**Comment by ktrutmann** [comment]
Done
